CREATE TABLE sub
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date    TIMESTAMP WITHOUT TIME ZONE,
    update_date     TIMESTAMP WITHOUT TIME ZONE,
    active          BOOLEAN,
    keyword_storage VARCHAR(2000),
    CONSTRAINT pk_sub PRIMARY KEY (id)
);