CREATE TABLE notice
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    update_date  TIMESTAMP WITHOUT TIME ZONE,
    active       BOOLEAN,
    text         TEXT,
    people_id    VARCHAR(36),
    CONSTRAINT pk_notice PRIMARY KEY (id)
);

ALTER TABLE notice
    ADD CONSTRAINT FK_NOTICE_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES people (id);